support env with http
armosec/kubescape pull request #500
Opened 2022-05-03 10:04 UTC by Daniel-GrunbergerCA

Useful for running with --env=http://localhost:7555. 
Up until now it was needed to switch all https to http

2022-05-03 11:25 UTC, dwertent requested changes

2022-05-03 11:25 UTC, dwertent commented on core/pkg/resultshandling/reporter/v1/reporteventreceiverutils.go
> +	if strings.Contains(urlObj.Host, "http://") {
Why not call a function that can parse the http/https?

2022-05-08 13:41 UTC, Bezbran requested changes
1. this should be applied for all URLs, not only event receiver
2. We are missing here a unitests

2022-05-11 05:26 UTC, dwertent commented on core/pkg/resultshandling/reporter/v2/reporteventreceiverutils.go
> +	if strings.Contains(host, "http://") {
What if the url contains `https://`?

2022-05-16 08:59 UTC, Daniel-GrunbergerCA commented on core/pkg/resultshandling/reporter/v2/reporteventreceiverutils.go
> +	if strings.Contains(host, "http://") {
Then it does not pass this condition

2022-05-16 12:22 UTC, merged